---
apiVersion: v1
kind: Template
metadata:
  name: apostille
objects:
# Service
- kind: Service
  apiVersion: v1
  metadata:
    name: ${{ NAME }}
    labels:
      app: ${{ NAME }}
    annotations:
      prometheus.io/scrape: 'true'
  spec:
    ports:
      - name: default
        protocol: TCP
        port: ${{ CLUSTERIP_SERVICE_PORT  }}
        targetPort: ${{ CLUSTERIP_SERVICE_TARGET_PORT }}
    selector:
      app: ${{ NAME }}
    type: ClusterIP
# Deployment
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: ${{ NAME }}
    labels:
      app: ${{ NAME }}
  spec:
    replicas: ${{ REPLICA_COUNT }}
    selector:
      matchLabels:
        app: ${{ NAME }}
    template:
      metadata:
        labels:
          app: ${{ NAME }}
      spec:
        volumes:
          - name: apostille-config
            secret:
              secretName: ${{ APOSTILLE_SERVER_SECRET }}
              items:
                - key: config_prod_json
                  path: config.json
          - name: apostille-signer-config
            secret:
              secretName: ${{ APOSTILLE_SIGNER_CONFIG }}
              items:
                - key: signer_config_json
                  path: config.json
              defaultMode: 420
          - name: apostille-server-secret
            secret:
              secretName: ${{ APOSTILLE_SERVER_SECRET }}
              items:
                - key: tls_ca
                  path: ca.crt
                - key: tls_client_cert
                  path: client.crt
                - key: tls_client_key
                  path: client.key
                - key:
          - name: apostille-signer-secret
            secret:
              secretName: ${{ APOSTILLE_SIGNER_CONFIG }}
              items:
                - key: client_ca_file
                  path: ca.crt
                - key: tls_cert_file
                  path: cert.crt
                - key: tls_key_file
                  path: cert.key
        containers:
          - resources:
              limits:
                cpu: ${{ SERVER_CPU_LIMIT }}
                memory: ${{ SERVER_MEMORY_LIMIT }}
              requests:
                cpu: ${{ SERVER_CPU_REQUEST }}
                memory: ${{ SERVER_MEMORY_REQUEST }}
            name: apostille-server
            command:
              - apostille
            args:
              - -config=/etc/config/config.json
            env:
              - name: DB_URL
                valueFrom:
                  secretKeyRef:
                    name: ${{ APOSTILLE_SERVER_SECRET }}
                    key: db_url
              - name: ROOT_DB_URL
                valueFrom:
                  secretKeyRef:
                    name: ${{ APOSTILLE_SERVER_SECRET }}
                    key: db_root_url
            ports:
              - name: web
                containerPort: ${{ SERVER_WEB_PORT }}
                protocol: TCP
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - name: apostille-config
                mountPath: /etc/config
              - name: apostille-server-secret
                mountPath: /etc/secret
            image: ${{ SERVER_IMAGE }}
          - resources:
              limits:
                cpu: ${{ SIGNER_CPU_LIMIT }}
                memory: ${{ SIGNER_MEMORY_LIMIT }}
              requests:
                cpu: ${{ SIGNER_CPU_REQUEST }}
                memory: ${{ SIGNER_MEMORY_REQUEST }}
            name: apostille-signer
            command:
              - notary-signer
            args:
              - -config=/etc/config/config.json
            env:
              - name: NOTARY_SIGNER_TIMESTAMP_1
                valueFrom:
                  secretKeyRef:
                    name: ${{ APOSTILLE_SIGNER_CONFIG }}
                    key: notary_signer_timestamp_1_password
              - name: GOPATH
                value: /go/src
              - name: DB_URL
                valueFrom:
                  secretKeyRef:
                    name: ${{ APOSTILLE_SIGNER_CONFIG }}
                    key: db_url
            ports:
              - name: grpc
                containerPort: ${{ SIGNER_GRPC_PORT }}
                protocol: TCP
            imagePullPolicy: Always
            volumeMounts:
              - name: apostille-signer-config
                mountPath: /etc/config
              - name: apostille-signer-secret
                mountPath: /etc/secret
            image: ${{ SIGNER_IMAGE  }}
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
    strategy:
      type: ${{ STRATEGY  }}
      rollingUpdate:
        maxUnavailable: ${{ MAX_UNAVAILABLE }}
        maxSurge: ${{ MAX_SURGE }}
    minReadySeconds: ${{ MIN_READY_SECONDS }}
â€‹
parameters:
- name: NAME
  value: "apostille"
  displayName: name
  description: Defaults for Apostille.
- name: CLUSTERIP_SERVICE_PORT
  value: 4443
  displayName: clusterip service port
  description: Defaults for Apostille.
- name: CLUSTERIP_SERVICE_TARGET_PORT
  value: 4443
  displayName: clusterip target service port
  description: Defaults for Apostille.
- name: SERVER_WEB_PORT
  value: 4443
  displayName: apostille web port
  description: apostille server container web port.
- name: SIGNER_GRPC_PORT
  value: 7899
  displayName: apostille web port
  description: apostille server container web port.
- name: REPLICA_COUNT
  value: 1
  displayName: pod replicas
  description: the number of apostille pods
- name: APOSTILLE_SERVER_SECRET
  value: apostille-server-secret
  displayName: apostille server secret
  description: apostille server secret
- name: APOSTILLE_SIGNER_CONFIG
  value: apostille-signer-config
  displayName: apostille-signer-config
  description: apostille-signer-config
- name: STRATEGY
  value: RollingUpdate
  displayName: kubernetes deployment strategy
  description: kubernetes deployment strategy
- name: MAX_UNAVAILABLE
  value: 0
  displayName: maximum number of unavailable pods 
  description: maximum number of unavailable pods
- name: MAX_SURGE 
  value: 4
  displayName: maximum number of surged pods
  description: maximum number of surged pods
- name: MIN_READY_SECONDS
  value: 60
  displayName: minimum number of seconds for ready 
  description: minimum number of seconds for ready
- name: SERVER_CPU_LIMIT
  value: 1
  displayName: apostille server cpu limit
  description: apostille server cpu limit
- name: SERVER_CPU_REQUEST
  value: 1
  displayName: apostille server cpu request
  description: apostille server cpu request
- name: SERVER_MEMORY_LIMIT
  value: 4096Mi
  displayName: apostille memory cpu limit
  description: apostille memory cpu limit
- name: SERVER_MEMORY_REQUEST
  value: 4096Mi
  displayName: apostille memory cpu request
  description: apostille memory cpu request
- name: SIGNER_CPU_LIMIT
  value: 1
  displayName: apostille signer cpu limit
  description: apostille signer cpu limit
- name: SIGNER_CPU_REQUEST
  value: 1
  displayName: apostille signer cpu request
  description: apostille signer cpu request
- name: SIGNER_MEMORY_LIMIT
  value: 4096Mi
  displayName: apostille signer memory limit
  description: apostille signer memory limit
- name: SIGNER_MEMORY_REQUEST
  value: 4096Mi
  displayName: apostille signer memory request
  description: apostille signer memory request
- name: SERVER_IMAGE
  value: ""
  display: apostille server container image
  description: apostille server container image
- name: SIGNER_IMAGE
  value: ""
  display: apostille signer container image
  description: apostille signer container image

