kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.service }}
  namespace: {{ .Values.apostille_namespace }}
  labels:
    app: {{ .Values.service }}
  annotations:
    prometheus.io/scrape: 'true'
spec:
  ports:
    - name: default
      protocol: TCP
      port: 4443
      targetPort: 4443
  selector:
    app: {{ .Values.service }}
  type: ClusterIP
