name: apostille-app
description: a image validation server for quay
home: https://github.com/coreos-inc/apostille
sources: 
  - https://github.com/coreos-inc/apostille
maintainers:
  - name: Evan Cordell
    email: evan.cordell@coreos.com
  - name: Charlton Austin
    email: charlie.austin@coreos.com
